### ISSUE TITLE
Istio support?

### ISSUE THREAD

**Issue by eucariop** [gary-archer/oauth.cloudnative.deployment#7]
How to configure Token Hanlder for istio solution

**Comment by gary-archer** [comment]
A token handler would just run like any other API in Istio, with the usual service and deployment resources. The key differences would be that there is no need for certmanager, and that the ingress would work using Istio resources.

I have only used Istio sparingly, but a while back I did some ingress stuff that looked roughly like this, in case this provides you with any useful hints.

````
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: myapi-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https-myapi
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: mycompany-com-tls
    hosts:
    - api.mycompany.com
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: myapi-destinationrule
spec:
  host: myapi-svc
  trafficPolicy:
    tls:
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: myapi-virtualservice
spec:
  hosts:
  - api.example.com
  gateways:
  - myapi-gateway
  http:
  - route:
    - destination:
        host: myapi-svc
        port:
          number: 3000
```
